/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info */

#ifndef _Included_info
#define _Included_info
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
