/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestMain */

#ifndef _Included_TestMain
#define _Included_TestMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestMain
 * Method:    getWords
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TestMain_getWords
  (JNIEnv *, jclass);

/*
 * Class:     TestMain
 * Method:    unzipInfo
 * Signature: (Ljava/lang/String;)Linfo;
 */
JNIEXPORT jobject JNICALL Java_TestMain_unzipInfo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     TestMain
 * Method:    unzipNull
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TestMain_unzipNull
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
