/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestMain */

#ifndef _Included_TestMain
#define _Included_TestMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestMain
 * Method:    getInfo
 * Signature: ()Linfo;
 */
JNIEXPORT jobject JNICALL Java_TestMain_getInfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
