// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testData.proto

package glx.cn.sh;

public final class TestData {
  private TestData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LogTagOrBuilder extends
      // @@protoc_insertion_point(interface_extends:glx.cn.sh.LogTag)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 Key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required int32 Key = 1;</code>
     */
    int getKey();

    /**
     * <code>required int32 Value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required int32 Value = 2;</code>
     */
    int getValue();
  }
  /**
   * Protobuf type {@code glx.cn.sh.LogTag}
   */
  public static final class LogTag extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:glx.cn.sh.LogTag)
      LogTagOrBuilder {
    // Use LogTag.newBuilder() to construct.
    private LogTag(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LogTag(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LogTag defaultInstance;
    public static LogTag getDefaultInstance() {
      return defaultInstance;
    }

    public LogTag getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LogTag(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              key_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              value_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return glx.cn.sh.TestData.internal_static_glx_cn_sh_LogTag_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return glx.cn.sh.TestData.internal_static_glx_cn_sh_LogTag_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              glx.cn.sh.TestData.LogTag.class, glx.cn.sh.TestData.LogTag.Builder.class);
    }

    public static com.google.protobuf.Parser<LogTag> PARSER =
        new com.google.protobuf.AbstractParser<LogTag>() {
      public LogTag parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogTag(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LogTag> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int KEY_FIELD_NUMBER = 1;
    private int key_;
    /**
     * <code>required int32 Key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 Key = 1;</code>
     */
    public int getKey() {
      return key_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private int value_;
    /**
     * <code>required int32 Value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 Value = 2;</code>
     */
    public int getValue() {
      return value_;
    }

    private void initFields() {
      key_ = 0;
      value_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static glx.cn.sh.TestData.LogTag parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static glx.cn.sh.TestData.LogTag parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static glx.cn.sh.TestData.LogTag parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static glx.cn.sh.TestData.LogTag parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static glx.cn.sh.TestData.LogTag parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static glx.cn.sh.TestData.LogTag parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static glx.cn.sh.TestData.LogTag parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static glx.cn.sh.TestData.LogTag parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static glx.cn.sh.TestData.LogTag parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static glx.cn.sh.TestData.LogTag parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(glx.cn.sh.TestData.LogTag prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code glx.cn.sh.LogTag}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:glx.cn.sh.LogTag)
        glx.cn.sh.TestData.LogTagOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return glx.cn.sh.TestData.internal_static_glx_cn_sh_LogTag_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return glx.cn.sh.TestData.internal_static_glx_cn_sh_LogTag_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                glx.cn.sh.TestData.LogTag.class, glx.cn.sh.TestData.LogTag.Builder.class);
      }

      // Construct using glx.cn.sh.TestData.LogTag.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return glx.cn.sh.TestData.internal_static_glx_cn_sh_LogTag_descriptor;
      }

      public glx.cn.sh.TestData.LogTag getDefaultInstanceForType() {
        return glx.cn.sh.TestData.LogTag.getDefaultInstance();
      }

      public glx.cn.sh.TestData.LogTag build() {
        glx.cn.sh.TestData.LogTag result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public glx.cn.sh.TestData.LogTag buildPartial() {
        glx.cn.sh.TestData.LogTag result = new glx.cn.sh.TestData.LogTag(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof glx.cn.sh.TestData.LogTag) {
          return mergeFrom((glx.cn.sh.TestData.LogTag)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(glx.cn.sh.TestData.LogTag other) {
        if (other == glx.cn.sh.TestData.LogTag.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        glx.cn.sh.TestData.LogTag parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (glx.cn.sh.TestData.LogTag) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int key_ ;
      /**
       * <code>required int32 Key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 Key = 1;</code>
       */
      public int getKey() {
        return key_;
      }
      /**
       * <code>required int32 Key = 1;</code>
       */
      public Builder setKey(int value) {
        bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 Key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = 0;
        onChanged();
        return this;
      }

      private int value_ ;
      /**
       * <code>required int32 Value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 Value = 2;</code>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>required int32 Value = 2;</code>
       */
      public Builder setValue(int value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 Value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:glx.cn.sh.LogTag)
    }

    static {
      defaultInstance = new LogTag(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:glx.cn.sh.LogTag)
  }

  public interface SiteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:glx.cn.sh.Site)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 2;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code glx.cn.sh.Site}
   */
  public static final class Site extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:glx.cn.sh.Site)
      SiteOrBuilder {
    // Use Site.newBuilder() to construct.
    private Site(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Site(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Site defaultInstance;
    public static Site getDefaultInstance() {
      return defaultInstance;
    }

    public Site getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Site(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return glx.cn.sh.TestData.internal_static_glx_cn_sh_Site_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return glx.cn.sh.TestData.internal_static_glx_cn_sh_Site_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              glx.cn.sh.TestData.Site.class, glx.cn.sh.TestData.Site.Builder.class);
    }

    public static com.google.protobuf.Parser<Site> PARSER =
        new com.google.protobuf.AbstractParser<Site>() {
      public Site parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Site(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Site> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    private void initFields() {
      name_ = "";
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static glx.cn.sh.TestData.Site parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static glx.cn.sh.TestData.Site parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static glx.cn.sh.TestData.Site parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static glx.cn.sh.TestData.Site parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static glx.cn.sh.TestData.Site parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static glx.cn.sh.TestData.Site parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static glx.cn.sh.TestData.Site parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static glx.cn.sh.TestData.Site parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static glx.cn.sh.TestData.Site parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static glx.cn.sh.TestData.Site parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(glx.cn.sh.TestData.Site prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code glx.cn.sh.Site}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:glx.cn.sh.Site)
        glx.cn.sh.TestData.SiteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return glx.cn.sh.TestData.internal_static_glx_cn_sh_Site_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return glx.cn.sh.TestData.internal_static_glx_cn_sh_Site_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                glx.cn.sh.TestData.Site.class, glx.cn.sh.TestData.Site.Builder.class);
      }

      // Construct using glx.cn.sh.TestData.Site.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return glx.cn.sh.TestData.internal_static_glx_cn_sh_Site_descriptor;
      }

      public glx.cn.sh.TestData.Site getDefaultInstanceForType() {
        return glx.cn.sh.TestData.Site.getDefaultInstance();
      }

      public glx.cn.sh.TestData.Site build() {
        glx.cn.sh.TestData.Site result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public glx.cn.sh.TestData.Site buildPartial() {
        glx.cn.sh.TestData.Site result = new glx.cn.sh.TestData.Site(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof glx.cn.sh.TestData.Site) {
          return mergeFrom((glx.cn.sh.TestData.Site)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(glx.cn.sh.TestData.Site other) {
        if (other == glx.cn.sh.TestData.Site.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        glx.cn.sh.TestData.Site parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (glx.cn.sh.TestData.Site) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>required int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:glx.cn.sh.Site)
    }

    static {
      defaultInstance = new Site(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:glx.cn.sh.Site)
  }

  public interface LogGroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:glx.cn.sh.LogGroup)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
     */
    java.util.List<glx.cn.sh.TestData.LogTag> 
        getTagsList();
    /**
     * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
     */
    glx.cn.sh.TestData.LogTag getTags(int index);
    /**
     * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
     */
    int getTagsCount();
    /**
     * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
     */
    java.util.List<? extends glx.cn.sh.TestData.LogTagOrBuilder> 
        getTagsOrBuilderList();
    /**
     * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
     */
    glx.cn.sh.TestData.LogTagOrBuilder getTagsOrBuilder(
        int index);

    /**
     * <code>repeated .glx.cn.sh.Site site = 3;</code>
     */
    java.util.List<glx.cn.sh.TestData.Site> 
        getSiteList();
    /**
     * <code>repeated .glx.cn.sh.Site site = 3;</code>
     */
    glx.cn.sh.TestData.Site getSite(int index);
    /**
     * <code>repeated .glx.cn.sh.Site site = 3;</code>
     */
    int getSiteCount();
    /**
     * <code>repeated .glx.cn.sh.Site site = 3;</code>
     */
    java.util.List<? extends glx.cn.sh.TestData.SiteOrBuilder> 
        getSiteOrBuilderList();
    /**
     * <code>repeated .glx.cn.sh.Site site = 3;</code>
     */
    glx.cn.sh.TestData.SiteOrBuilder getSiteOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code glx.cn.sh.LogGroup}
   */
  public static final class LogGroup extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:glx.cn.sh.LogGroup)
      LogGroupOrBuilder {
    // Use LogGroup.newBuilder() to construct.
    private LogGroup(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LogGroup(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LogGroup defaultInstance;
    public static LogGroup getDefaultInstance() {
      return defaultInstance;
    }

    public LogGroup getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LogGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                tags_ = new java.util.ArrayList<glx.cn.sh.TestData.LogTag>();
                mutable_bitField0_ |= 0x00000002;
              }
              tags_.add(input.readMessage(glx.cn.sh.TestData.LogTag.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                site_ = new java.util.ArrayList<glx.cn.sh.TestData.Site>();
                mutable_bitField0_ |= 0x00000004;
              }
              site_.add(input.readMessage(glx.cn.sh.TestData.Site.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          tags_ = java.util.Collections.unmodifiableList(tags_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          site_ = java.util.Collections.unmodifiableList(site_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return glx.cn.sh.TestData.internal_static_glx_cn_sh_LogGroup_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return glx.cn.sh.TestData.internal_static_glx_cn_sh_LogGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              glx.cn.sh.TestData.LogGroup.class, glx.cn.sh.TestData.LogGroup.Builder.class);
    }

    public static com.google.protobuf.Parser<LogGroup> PARSER =
        new com.google.protobuf.AbstractParser<LogGroup>() {
      public LogGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogGroup(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LogGroup> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAGS_FIELD_NUMBER = 2;
    private java.util.List<glx.cn.sh.TestData.LogTag> tags_;
    /**
     * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
     */
    public java.util.List<glx.cn.sh.TestData.LogTag> getTagsList() {
      return tags_;
    }
    /**
     * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
     */
    public java.util.List<? extends glx.cn.sh.TestData.LogTagOrBuilder> 
        getTagsOrBuilderList() {
      return tags_;
    }
    /**
     * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
     */
    public glx.cn.sh.TestData.LogTag getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
     */
    public glx.cn.sh.TestData.LogTagOrBuilder getTagsOrBuilder(
        int index) {
      return tags_.get(index);
    }

    public static final int SITE_FIELD_NUMBER = 3;
    private java.util.List<glx.cn.sh.TestData.Site> site_;
    /**
     * <code>repeated .glx.cn.sh.Site site = 3;</code>
     */
    public java.util.List<glx.cn.sh.TestData.Site> getSiteList() {
      return site_;
    }
    /**
     * <code>repeated .glx.cn.sh.Site site = 3;</code>
     */
    public java.util.List<? extends glx.cn.sh.TestData.SiteOrBuilder> 
        getSiteOrBuilderList() {
      return site_;
    }
    /**
     * <code>repeated .glx.cn.sh.Site site = 3;</code>
     */
    public int getSiteCount() {
      return site_.size();
    }
    /**
     * <code>repeated .glx.cn.sh.Site site = 3;</code>
     */
    public glx.cn.sh.TestData.Site getSite(int index) {
      return site_.get(index);
    }
    /**
     * <code>repeated .glx.cn.sh.Site site = 3;</code>
     */
    public glx.cn.sh.TestData.SiteOrBuilder getSiteOrBuilder(
        int index) {
      return site_.get(index);
    }

    private void initFields() {
      name_ = "";
      tags_ = java.util.Collections.emptyList();
      site_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getTagsCount(); i++) {
        if (!getTags(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getSiteCount(); i++) {
        if (!getSite(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      for (int i = 0; i < tags_.size(); i++) {
        output.writeMessage(2, tags_.get(i));
      }
      for (int i = 0; i < site_.size(); i++) {
        output.writeMessage(3, site_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      for (int i = 0; i < tags_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, tags_.get(i));
      }
      for (int i = 0; i < site_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, site_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static glx.cn.sh.TestData.LogGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static glx.cn.sh.TestData.LogGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static glx.cn.sh.TestData.LogGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static glx.cn.sh.TestData.LogGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static glx.cn.sh.TestData.LogGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static glx.cn.sh.TestData.LogGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static glx.cn.sh.TestData.LogGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static glx.cn.sh.TestData.LogGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static glx.cn.sh.TestData.LogGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static glx.cn.sh.TestData.LogGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(glx.cn.sh.TestData.LogGroup prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code glx.cn.sh.LogGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:glx.cn.sh.LogGroup)
        glx.cn.sh.TestData.LogGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return glx.cn.sh.TestData.internal_static_glx_cn_sh_LogGroup_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return glx.cn.sh.TestData.internal_static_glx_cn_sh_LogGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                glx.cn.sh.TestData.LogGroup.class, glx.cn.sh.TestData.LogGroup.Builder.class);
      }

      // Construct using glx.cn.sh.TestData.LogGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTagsFieldBuilder();
          getSiteFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (tagsBuilder_ == null) {
          tags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          tagsBuilder_.clear();
        }
        if (siteBuilder_ == null) {
          site_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          siteBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return glx.cn.sh.TestData.internal_static_glx_cn_sh_LogGroup_descriptor;
      }

      public glx.cn.sh.TestData.LogGroup getDefaultInstanceForType() {
        return glx.cn.sh.TestData.LogGroup.getDefaultInstance();
      }

      public glx.cn.sh.TestData.LogGroup build() {
        glx.cn.sh.TestData.LogGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public glx.cn.sh.TestData.LogGroup buildPartial() {
        glx.cn.sh.TestData.LogGroup result = new glx.cn.sh.TestData.LogGroup(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (tagsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            tags_ = java.util.Collections.unmodifiableList(tags_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.tags_ = tags_;
        } else {
          result.tags_ = tagsBuilder_.build();
        }
        if (siteBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            site_ = java.util.Collections.unmodifiableList(site_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.site_ = site_;
        } else {
          result.site_ = siteBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof glx.cn.sh.TestData.LogGroup) {
          return mergeFrom((glx.cn.sh.TestData.LogGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(glx.cn.sh.TestData.LogGroup other) {
        if (other == glx.cn.sh.TestData.LogGroup.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (tagsBuilder_ == null) {
          if (!other.tags_.isEmpty()) {
            if (tags_.isEmpty()) {
              tags_ = other.tags_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTagsIsMutable();
              tags_.addAll(other.tags_);
            }
            onChanged();
          }
        } else {
          if (!other.tags_.isEmpty()) {
            if (tagsBuilder_.isEmpty()) {
              tagsBuilder_.dispose();
              tagsBuilder_ = null;
              tags_ = other.tags_;
              bitField0_ = (bitField0_ & ~0x00000002);
              tagsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTagsFieldBuilder() : null;
            } else {
              tagsBuilder_.addAllMessages(other.tags_);
            }
          }
        }
        if (siteBuilder_ == null) {
          if (!other.site_.isEmpty()) {
            if (site_.isEmpty()) {
              site_ = other.site_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureSiteIsMutable();
              site_.addAll(other.site_);
            }
            onChanged();
          }
        } else {
          if (!other.site_.isEmpty()) {
            if (siteBuilder_.isEmpty()) {
              siteBuilder_.dispose();
              siteBuilder_ = null;
              site_ = other.site_;
              bitField0_ = (bitField0_ & ~0x00000004);
              siteBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSiteFieldBuilder() : null;
            } else {
              siteBuilder_.addAllMessages(other.site_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getTagsCount(); i++) {
          if (!getTags(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getSiteCount(); i++) {
          if (!getSite(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        glx.cn.sh.TestData.LogGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (glx.cn.sh.TestData.LogGroup) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<glx.cn.sh.TestData.LogTag> tags_ =
        java.util.Collections.emptyList();
      private void ensureTagsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          tags_ = new java.util.ArrayList<glx.cn.sh.TestData.LogTag>(tags_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          glx.cn.sh.TestData.LogTag, glx.cn.sh.TestData.LogTag.Builder, glx.cn.sh.TestData.LogTagOrBuilder> tagsBuilder_;

      /**
       * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
       */
      public java.util.List<glx.cn.sh.TestData.LogTag> getTagsList() {
        if (tagsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tags_);
        } else {
          return tagsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
       */
      public int getTagsCount() {
        if (tagsBuilder_ == null) {
          return tags_.size();
        } else {
          return tagsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
       */
      public glx.cn.sh.TestData.LogTag getTags(int index) {
        if (tagsBuilder_ == null) {
          return tags_.get(index);
        } else {
          return tagsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
       */
      public Builder setTags(
          int index, glx.cn.sh.TestData.LogTag value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.set(index, value);
          onChanged();
        } else {
          tagsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
       */
      public Builder setTags(
          int index, glx.cn.sh.TestData.LogTag.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.set(index, builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
       */
      public Builder addTags(glx.cn.sh.TestData.LogTag value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.add(value);
          onChanged();
        } else {
          tagsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
       */
      public Builder addTags(
          int index, glx.cn.sh.TestData.LogTag value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.add(index, value);
          onChanged();
        } else {
          tagsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
       */
      public Builder addTags(
          glx.cn.sh.TestData.LogTag.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.add(builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
       */
      public Builder addTags(
          int index, glx.cn.sh.TestData.LogTag.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.add(index, builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
       */
      public Builder addAllTags(
          java.lang.Iterable<? extends glx.cn.sh.TestData.LogTag> values) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tags_);
          onChanged();
        } else {
          tagsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
       */
      public Builder clearTags() {
        if (tagsBuilder_ == null) {
          tags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          tagsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
       */
      public Builder removeTags(int index) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.remove(index);
          onChanged();
        } else {
          tagsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
       */
      public glx.cn.sh.TestData.LogTag.Builder getTagsBuilder(
          int index) {
        return getTagsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
       */
      public glx.cn.sh.TestData.LogTagOrBuilder getTagsOrBuilder(
          int index) {
        if (tagsBuilder_ == null) {
          return tags_.get(index);  } else {
          return tagsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
       */
      public java.util.List<? extends glx.cn.sh.TestData.LogTagOrBuilder> 
           getTagsOrBuilderList() {
        if (tagsBuilder_ != null) {
          return tagsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tags_);
        }
      }
      /**
       * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
       */
      public glx.cn.sh.TestData.LogTag.Builder addTagsBuilder() {
        return getTagsFieldBuilder().addBuilder(
            glx.cn.sh.TestData.LogTag.getDefaultInstance());
      }
      /**
       * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
       */
      public glx.cn.sh.TestData.LogTag.Builder addTagsBuilder(
          int index) {
        return getTagsFieldBuilder().addBuilder(
            index, glx.cn.sh.TestData.LogTag.getDefaultInstance());
      }
      /**
       * <code>repeated .glx.cn.sh.LogTag tags = 2;</code>
       */
      public java.util.List<glx.cn.sh.TestData.LogTag.Builder> 
           getTagsBuilderList() {
        return getTagsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          glx.cn.sh.TestData.LogTag, glx.cn.sh.TestData.LogTag.Builder, glx.cn.sh.TestData.LogTagOrBuilder> 
          getTagsFieldBuilder() {
        if (tagsBuilder_ == null) {
          tagsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              glx.cn.sh.TestData.LogTag, glx.cn.sh.TestData.LogTag.Builder, glx.cn.sh.TestData.LogTagOrBuilder>(
                  tags_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          tags_ = null;
        }
        return tagsBuilder_;
      }

      private java.util.List<glx.cn.sh.TestData.Site> site_ =
        java.util.Collections.emptyList();
      private void ensureSiteIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          site_ = new java.util.ArrayList<glx.cn.sh.TestData.Site>(site_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          glx.cn.sh.TestData.Site, glx.cn.sh.TestData.Site.Builder, glx.cn.sh.TestData.SiteOrBuilder> siteBuilder_;

      /**
       * <code>repeated .glx.cn.sh.Site site = 3;</code>
       */
      public java.util.List<glx.cn.sh.TestData.Site> getSiteList() {
        if (siteBuilder_ == null) {
          return java.util.Collections.unmodifiableList(site_);
        } else {
          return siteBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .glx.cn.sh.Site site = 3;</code>
       */
      public int getSiteCount() {
        if (siteBuilder_ == null) {
          return site_.size();
        } else {
          return siteBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .glx.cn.sh.Site site = 3;</code>
       */
      public glx.cn.sh.TestData.Site getSite(int index) {
        if (siteBuilder_ == null) {
          return site_.get(index);
        } else {
          return siteBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .glx.cn.sh.Site site = 3;</code>
       */
      public Builder setSite(
          int index, glx.cn.sh.TestData.Site value) {
        if (siteBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSiteIsMutable();
          site_.set(index, value);
          onChanged();
        } else {
          siteBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .glx.cn.sh.Site site = 3;</code>
       */
      public Builder setSite(
          int index, glx.cn.sh.TestData.Site.Builder builderForValue) {
        if (siteBuilder_ == null) {
          ensureSiteIsMutable();
          site_.set(index, builderForValue.build());
          onChanged();
        } else {
          siteBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .glx.cn.sh.Site site = 3;</code>
       */
      public Builder addSite(glx.cn.sh.TestData.Site value) {
        if (siteBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSiteIsMutable();
          site_.add(value);
          onChanged();
        } else {
          siteBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .glx.cn.sh.Site site = 3;</code>
       */
      public Builder addSite(
          int index, glx.cn.sh.TestData.Site value) {
        if (siteBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSiteIsMutable();
          site_.add(index, value);
          onChanged();
        } else {
          siteBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .glx.cn.sh.Site site = 3;</code>
       */
      public Builder addSite(
          glx.cn.sh.TestData.Site.Builder builderForValue) {
        if (siteBuilder_ == null) {
          ensureSiteIsMutable();
          site_.add(builderForValue.build());
          onChanged();
        } else {
          siteBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .glx.cn.sh.Site site = 3;</code>
       */
      public Builder addSite(
          int index, glx.cn.sh.TestData.Site.Builder builderForValue) {
        if (siteBuilder_ == null) {
          ensureSiteIsMutable();
          site_.add(index, builderForValue.build());
          onChanged();
        } else {
          siteBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .glx.cn.sh.Site site = 3;</code>
       */
      public Builder addAllSite(
          java.lang.Iterable<? extends glx.cn.sh.TestData.Site> values) {
        if (siteBuilder_ == null) {
          ensureSiteIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, site_);
          onChanged();
        } else {
          siteBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .glx.cn.sh.Site site = 3;</code>
       */
      public Builder clearSite() {
        if (siteBuilder_ == null) {
          site_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          siteBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .glx.cn.sh.Site site = 3;</code>
       */
      public Builder removeSite(int index) {
        if (siteBuilder_ == null) {
          ensureSiteIsMutable();
          site_.remove(index);
          onChanged();
        } else {
          siteBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .glx.cn.sh.Site site = 3;</code>
       */
      public glx.cn.sh.TestData.Site.Builder getSiteBuilder(
          int index) {
        return getSiteFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .glx.cn.sh.Site site = 3;</code>
       */
      public glx.cn.sh.TestData.SiteOrBuilder getSiteOrBuilder(
          int index) {
        if (siteBuilder_ == null) {
          return site_.get(index);  } else {
          return siteBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .glx.cn.sh.Site site = 3;</code>
       */
      public java.util.List<? extends glx.cn.sh.TestData.SiteOrBuilder> 
           getSiteOrBuilderList() {
        if (siteBuilder_ != null) {
          return siteBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(site_);
        }
      }
      /**
       * <code>repeated .glx.cn.sh.Site site = 3;</code>
       */
      public glx.cn.sh.TestData.Site.Builder addSiteBuilder() {
        return getSiteFieldBuilder().addBuilder(
            glx.cn.sh.TestData.Site.getDefaultInstance());
      }
      /**
       * <code>repeated .glx.cn.sh.Site site = 3;</code>
       */
      public glx.cn.sh.TestData.Site.Builder addSiteBuilder(
          int index) {
        return getSiteFieldBuilder().addBuilder(
            index, glx.cn.sh.TestData.Site.getDefaultInstance());
      }
      /**
       * <code>repeated .glx.cn.sh.Site site = 3;</code>
       */
      public java.util.List<glx.cn.sh.TestData.Site.Builder> 
           getSiteBuilderList() {
        return getSiteFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          glx.cn.sh.TestData.Site, glx.cn.sh.TestData.Site.Builder, glx.cn.sh.TestData.SiteOrBuilder> 
          getSiteFieldBuilder() {
        if (siteBuilder_ == null) {
          siteBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              glx.cn.sh.TestData.Site, glx.cn.sh.TestData.Site.Builder, glx.cn.sh.TestData.SiteOrBuilder>(
                  site_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          site_ = null;
        }
        return siteBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:glx.cn.sh.LogGroup)
    }

    static {
      defaultInstance = new LogGroup(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:glx.cn.sh.LogGroup)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glx_cn_sh_LogTag_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_glx_cn_sh_LogTag_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glx_cn_sh_Site_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_glx_cn_sh_Site_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glx_cn_sh_LogGroup_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_glx_cn_sh_LogGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016testData.proto\022\tglx.cn.sh\"$\n\006LogTag\022\013\n" +
      "\003Key\030\001 \002(\005\022\r\n\005Value\030\002 \002(\005\" \n\004Site\022\014\n\004nam" +
      "e\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\"X\n\010LogGroup\022\014\n\004name\030" +
      "\001 \001(\t\022\037\n\004tags\030\002 \003(\0132\021.glx.cn.sh.LogTag\022\035" +
      "\n\004site\030\003 \003(\0132\017.glx.cn.sh.Site"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_glx_cn_sh_LogTag_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_glx_cn_sh_LogTag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_glx_cn_sh_LogTag_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_glx_cn_sh_Site_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_glx_cn_sh_Site_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_glx_cn_sh_Site_descriptor,
        new java.lang.String[] { "Name", "Id", });
    internal_static_glx_cn_sh_LogGroup_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_glx_cn_sh_LogGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_glx_cn_sh_LogGroup_descriptor,
        new java.lang.String[] { "Name", "Tags", "Site", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
