// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testData.proto

#ifndef PROTOBUF_testData_2eproto__INCLUDED
#define PROTOBUF_testData_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace org {
namespace apache {
namespace metis {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_testData_2eproto();
void protobuf_AssignDesc_testData_2eproto();
void protobuf_ShutdownFile_testData_2eproto();

class LogTag;
class LogGroup;

// ===================================================================

class LogTag : public ::google::protobuf::Message {
 public:
  LogTag();
  virtual ~LogTag();

  LogTag(const LogTag& from);

  inline LogTag& operator=(const LogTag& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LogTag& default_instance();

  void Swap(LogTag* other);

  // implements Message ----------------------------------------------

  LogTag* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LogTag& from);
  void MergeFrom(const LogTag& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string Key = 1;
  inline bool has_key() const;
  inline void clear_key();
  static const int kKeyFieldNumber = 1;
  inline const ::std::string& key() const;
  inline void set_key(const ::std::string& value);
  inline void set_key(const char* value);
  inline void set_key(const char* value, size_t size);
  inline ::std::string* mutable_key();
  inline ::std::string* release_key();
  inline void set_allocated_key(::std::string* key);

  // required string Value = 2;
  inline bool has_value() const;
  inline void clear_value();
  static const int kValueFieldNumber = 2;
  inline const ::std::string& value() const;
  inline void set_value(const ::std::string& value);
  inline void set_value(const char* value);
  inline void set_value(const char* value, size_t size);
  inline ::std::string* mutable_value();
  inline ::std::string* release_value();
  inline void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:org.apache.metis.LogTag)
 private:
  inline void set_has_key();
  inline void clear_has_key();
  inline void set_has_value();
  inline void clear_has_value();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* key_;
  ::std::string* value_;
  friend void  protobuf_AddDesc_testData_2eproto();
  friend void protobuf_AssignDesc_testData_2eproto();
  friend void protobuf_ShutdownFile_testData_2eproto();

  void InitAsDefaultInstance();
  static LogTag* default_instance_;
};
// -------------------------------------------------------------------

class LogGroup : public ::google::protobuf::Message {
 public:
  LogGroup();
  virtual ~LogGroup();

  LogGroup(const LogGroup& from);

  inline LogGroup& operator=(const LogGroup& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LogGroup& default_instance();

  void Swap(LogGroup* other);

  // implements Message ----------------------------------------------

  LogGroup* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LogGroup& from);
  void MergeFrom(const LogGroup& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // repeated .org.apache.metis.LogTag tags = 2;
  inline int tags_size() const;
  inline void clear_tags();
  static const int kTagsFieldNumber = 2;
  inline const ::org::apache::metis::LogTag& tags(int index) const;
  inline ::org::apache::metis::LogTag* mutable_tags(int index);
  inline ::org::apache::metis::LogTag* add_tags();
  inline const ::google::protobuf::RepeatedPtrField< ::org::apache::metis::LogTag >&
      tags() const;
  inline ::google::protobuf::RepeatedPtrField< ::org::apache::metis::LogTag >*
      mutable_tags();

  // @@protoc_insertion_point(class_scope:org.apache.metis.LogGroup)
 private:
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::google::protobuf::RepeatedPtrField< ::org::apache::metis::LogTag > tags_;
  friend void  protobuf_AddDesc_testData_2eproto();
  friend void protobuf_AssignDesc_testData_2eproto();
  friend void protobuf_ShutdownFile_testData_2eproto();

  void InitAsDefaultInstance();
  static LogGroup* default_instance_;
};
// ===================================================================


// ===================================================================

// LogTag

// required string Key = 1;
inline bool LogTag::has_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LogTag::set_has_key() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LogTag::clear_has_key() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LogTag::clear_key() {
  if (key_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_->clear();
  }
  clear_has_key();
}
inline const ::std::string& LogTag::key() const {
  // @@protoc_insertion_point(field_get:org.apache.metis.LogTag.Key)
  return *key_;
}
inline void LogTag::set_key(const ::std::string& value) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_ = new ::std::string;
  }
  key_->assign(value);
  // @@protoc_insertion_point(field_set:org.apache.metis.LogTag.Key)
}
inline void LogTag::set_key(const char* value) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_ = new ::std::string;
  }
  key_->assign(value);
  // @@protoc_insertion_point(field_set_char:org.apache.metis.LogTag.Key)
}
inline void LogTag::set_key(const char* value, size_t size) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_ = new ::std::string;
  }
  key_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:org.apache.metis.LogTag.Key)
}
inline ::std::string* LogTag::mutable_key() {
  set_has_key();
  if (key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:org.apache.metis.LogTag.Key)
  return key_;
}
inline ::std::string* LogTag::release_key() {
  clear_has_key();
  if (key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = key_;
    key_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void LogTag::set_allocated_key(::std::string* key) {
  if (key_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete key_;
  }
  if (key) {
    set_has_key();
    key_ = key;
  } else {
    clear_has_key();
    key_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:org.apache.metis.LogTag.Key)
}

// required string Value = 2;
inline bool LogTag::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LogTag::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LogTag::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LogTag::clear_value() {
  if (value_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    value_->clear();
  }
  clear_has_value();
}
inline const ::std::string& LogTag::value() const {
  // @@protoc_insertion_point(field_get:org.apache.metis.LogTag.Value)
  return *value_;
}
inline void LogTag::set_value(const ::std::string& value) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    value_ = new ::std::string;
  }
  value_->assign(value);
  // @@protoc_insertion_point(field_set:org.apache.metis.LogTag.Value)
}
inline void LogTag::set_value(const char* value) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    value_ = new ::std::string;
  }
  value_->assign(value);
  // @@protoc_insertion_point(field_set_char:org.apache.metis.LogTag.Value)
}
inline void LogTag::set_value(const char* value, size_t size) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    value_ = new ::std::string;
  }
  value_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:org.apache.metis.LogTag.Value)
}
inline ::std::string* LogTag::mutable_value() {
  set_has_value();
  if (value_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    value_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:org.apache.metis.LogTag.Value)
  return value_;
}
inline ::std::string* LogTag::release_value() {
  clear_has_value();
  if (value_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = value_;
    value_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void LogTag::set_allocated_value(::std::string* value) {
  if (value_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete value_;
  }
  if (value) {
    set_has_value();
    value_ = value;
  } else {
    clear_has_value();
    value_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:org.apache.metis.LogTag.Value)
}

// -------------------------------------------------------------------

// LogGroup

// optional string name = 1;
inline bool LogGroup::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LogGroup::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LogGroup::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LogGroup::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& LogGroup::name() const {
  // @@protoc_insertion_point(field_get:org.apache.metis.LogGroup.name)
  return *name_;
}
inline void LogGroup::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:org.apache.metis.LogGroup.name)
}
inline void LogGroup::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:org.apache.metis.LogGroup.name)
}
inline void LogGroup::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:org.apache.metis.LogGroup.name)
}
inline ::std::string* LogGroup::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:org.apache.metis.LogGroup.name)
  return name_;
}
inline ::std::string* LogGroup::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void LogGroup::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:org.apache.metis.LogGroup.name)
}

// repeated .org.apache.metis.LogTag tags = 2;
inline int LogGroup::tags_size() const {
  return tags_.size();
}
inline void LogGroup::clear_tags() {
  tags_.Clear();
}
inline const ::org::apache::metis::LogTag& LogGroup::tags(int index) const {
  // @@protoc_insertion_point(field_get:org.apache.metis.LogGroup.tags)
  return tags_.Get(index);
}
inline ::org::apache::metis::LogTag* LogGroup::mutable_tags(int index) {
  // @@protoc_insertion_point(field_mutable:org.apache.metis.LogGroup.tags)
  return tags_.Mutable(index);
}
inline ::org::apache::metis::LogTag* LogGroup::add_tags() {
  // @@protoc_insertion_point(field_add:org.apache.metis.LogGroup.tags)
  return tags_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::org::apache::metis::LogTag >&
LogGroup::tags() const {
  // @@protoc_insertion_point(field_list:org.apache.metis.LogGroup.tags)
  return tags_;
}
inline ::google::protobuf::RepeatedPtrField< ::org::apache::metis::LogTag >*
LogGroup::mutable_tags() {
  // @@protoc_insertion_point(field_mutable_list:org.apache.metis.LogGroup.tags)
  return &tags_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace metis
}  // namespace apache
}  // namespace org

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_testData_2eproto__INCLUDED
